In [27]:
%load_ext autoreload
%autoreload 2

from trees.experiment import debug
from trees.causal_tree import CT, CTP
from trees.causal_forest import CF, CFT
from trees.scanners import Exhaustive, Greedy

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Greedy

In [19]:
debug(CT, Greedy)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Computing overlap matrix

100%|██████████| 102/102 [00:00<00:00, 15952.68it/s]

Overlap matrix computed
[CT on D (Greedy)] Offline time: 0.09
User condition: feature_6 > -0.203 Selectivity: 0.584
[CT on D (Greedy)] Online time: 0.01, Total Splits: 102, Valid: 58
[CT on D (Greedy)] get topK in 0.0

,id,condition,combined,features,t_est,T0,T1,depth,algorithm,rows,total_options,validate_time,overlap,score,t,scan_method,scan_time,valid_options
0,97,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (1.836, 3.728), 'feature_4': (-3...",4,4.474,0.75,5.23,7,CT on D (Greedy),44,102,0.01,0.360768,0.731056,2.750,Greedy,0.0,58
1,13,feature_0 <= -1.656 AND feature_8 > 0.684 AND ...,"{'feature_0': (-4.295, -1.656), 'feature_8': (...",2,4.295,3.88,-0.41,3,CT on D (Greedy),39,102,0.01,0.000000,0.894979,1.444,Greedy,0.0,58
2,88,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (0.901, 1.836), 'feature_4': (-3...",5,2.822,0.54,3.36,8,CT on D (Greedy),47,102,0.01,0.085638,0.716699,2.090,Greedy,0.0,58
3,10,feature_0 <= -1.656 AND feature_8 <= 0.684 AND...,"{'feature_0': (-4.295, -1.656), 'feature_8': (...",3,2.456,2.13,-0.33,4,CT on D (Greedy),42,102,0.01,0.000000,0.725860,1.345,Greedy,0.0,58
4,17,feature_0 > -1.656 AND feature_0 <= -0.41 AND ...,"{'feature_0': (-1.656, -0.41), 'feature_4': (-...",2,2.365,-0.93,1.43,3,CT on D (Greedy),29,102,0.01,0.000000,0.717491,0.235,Greedy,0.0,58

In [20]:
debug(CTP, Greedy)

[CT on P (Greedy)] Offline time: 0.0
User condition: feature_6 > -0.203 Selectivity: 0.584
Computing overlap matrix

100%|██████████| 110/110 [00:00<00:00, 12667.44it/s]

Overlap matrix computed
[CT on P (Greedy)] Online time: 0.08, Total Splits: 110, Valid: 102
[CT on P (Greedy)] get topK in 0.0

,id,condition,combined,features,t_est,T0,T1,depth,algorithm,rows,total_options,validate_time,overlap,score,t,scan_method,scan_time,valid_options
0,98,feature_0 > 0.172 AND feature_1 > -1.881 AND f...,"{'feature_0': (0.172, 1.804), 'feature_1': (1....",4,4.965,0.51,5.47,8,CT on P (Greedy),98,110,0.02,0.257347,0.871326,2.631,Greedy,0.0,102
1,60,feature_0 <= 0.172 AND feature_0 > -1.769 AND ...,"{'feature_0': (-0.677, 0.172), 'feature_1': (1...",4,4.102,-0.62,3.48,6,CT on P (Greedy),51,110,0.02,0.245320,0.790432,1.499,Greedy,0.0,102
2,97,feature_0 > 0.172 AND feature_1 > -1.881 AND f...,"{'feature_0': (0.172, 1.804), 'feature_1': (1....",3,3.975,1.33,5.30,7,CT on P (Greedy),156,110,0.02,0.257347,0.771628,2.617,Greedy,0.0,102
3,6,feature_0 <= 0.172 AND feature_0 <= -1.769 AND...,"{'feature_0': (-4.295, -2.077), 'feature_5': (...",2,3.562,1.81,-1.76,4,CT on P (Greedy),50,110,0.02,0.000000,0.858711,1.577,Greedy,0.0,102
4,5,feature_0 <= 0.172 AND feature_0 <= -1.769 AND...,"{'feature_0': (-4.295, -1.769), 'feature_5': (...",2,2.702,2.05,-0.65,3,CT on P (Greedy),100,110,0.02,0.000000,0.772105,1.380,Greedy,0.0,102

In [21]:
debug(CF, scanner=Greedy)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Computing overlap matrix

100%|██████████| 4950/4950 [00:18<00:00, 270.43it/s]

Overlap matrix computed
[CF (Greedy)] Offline time: 22.09
User condition: feature_5 <= 0.665 Selectivity: 0.7458
[CF (Greedy)] Online time: 0.73, Total Splits: 4950, Valid: 4392
[CF (Greedy)] get topK in 0.04

,id,condition,combined,features,t_est,depth,algorithm,rows,total_options,validate_time,overlap,score,t,scan_method,scan_time,valid_options
0,2354,feature_0 <= 0.418 AND feature_1 > -0.072 AND ...,"{'feature_0': (-4.295, 0.418), 'feature_1': (-...",5,4.484,8,CF (Greedy),100,4950,0.73,0.000000,0.885886,0.612,Greedy,0.04,4392
1,2383,feature_0 > 0.418 AND feature_0 <= 1.672 AND f...,"{'feature_0': (0.418, 1.672), 'feature_1': (1....",2,4.381,4,CF (Greedy),111,4950,0.73,0.022961,0.865542,2.654,Greedy,0.04,4392
2,3342,feature_0 > 0.931 AND feature_1 <= 1.099 AND f...,"{'feature_0': (0.931, 1.074), 'feature_1': (-4...",3,4.039,5,CF (Greedy),113,4950,0.73,0.000000,0.847590,1.666,Greedy,0.04,4392
3,1277,feature_0 > 0.085 AND feature_1 > 0.477 AND fe...,"{'feature_0': (0.085, 1.304), 'feature_1': (0....",5,3.971,8,CF (Greedy),106,4950,0.73,0.000000,0.841738,1.980,Greedy,0.04,4392
4,609,feature_0 <= -0.163 AND feature_0 <= -1.723 AN...,"{'feature_0': (-4.295, -1.723), 'feature_6': (...",2,3.901,3,CF (Greedy),180,4950,0.73,0.000000,0.835714,1.381,Greedy,0.04,4392

In [25]:
debug(CFT, scanner=Greedy)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Computing overlap matrix

100%|██████████| 258/258 [00:00<00:00, 5551.49it/s]

Overlap matrix computed
[CF SingleTree (Greedy)] Offline time: 7.61
User condition: feature_5 <= 0.665 Selectivity: 0.7458
[CF SingleTree (Greedy)] Online time: 0.04, Total Splits: 258, Valid: 255
[CF SingleTree (Greedy)] get topK in 0.0

,id,condition,combined,features,t_est,depth,algorithm,rows,total_options,validate_time,overlap,score,t,scan_method,scan_time,valid_options
0,237,feature_0 > 0.076 AND feature_0 > 1.597 AND fe...,"{'feature_0': (1.597, 1.834), 'feature_1': (0....",2,2.352,5,CF SingleTree (Greedy),29,258,0.04,0.084429,0.858194,2.901,Greedy,0.0,255
1,241,feature_0 > 0.076 AND feature_0 > 1.597 AND fe...,"{'feature_0': (1.834, 1.975), 'feature_1': (-4...",2,2.287,5,CF SingleTree (Greedy),24,258,0.04,0.003960,0.887363,2.224,Greedy,0.0,255
2,228,feature_0 > 0.076 AND feature_0 > 1.597 AND fe...,"{'feature_0': (1.597, 1.834)}",1,2.156,3,CF SingleTree (Greedy),173,258,0.04,0.000000,0.867041,2.568,Greedy,0.0,255
3,209,feature_0 > 0.076 AND feature_0 <= 1.597 AND f...,"{'feature_0': (1.05, 1.597), 'feature_1': (1.1...",2,2.093,7,CF SingleTree (Greedy),22,258,0.04,0.019146,0.846743,2.771,Greedy,0.0,255
4,207,feature_0 > 0.076 AND feature_0 <= 1.597 AND f...,"{'feature_0': (0.756, 1.597), 'feature_1': (1....",2,2.030,6,CF SingleTree (Greedy),50,258,0.04,0.019146,0.836017,2.565,Greedy,0.0,255

# Exhaustive

In [24]:
debug(CT, Exhaustive)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Computing overlap matrix

100%|██████████| 102/102 [00:00<00:00, 15271.61it/s]

Overlap matrix computed
[CT on D (Exhaustive)] Offline time: 0.09
User condition: feature_6 > -0.203 Selectivity: 0.584
[CT on D (Exhaustive)] Online time: 0.01, Total Splits: 102, Valid: 58

4582116it [00:16, 269612.73it/s]

[CT on D (Exhaustive)] get topK in 17.0

,id,condition,combined,features,t_est,T0,T1,depth,algorithm,rows,total_options,validate_time,overlap,score,t,scan_method,scan_time,valid_options
0,10,feature_0 <= -1.656 AND feature_8 <= 0.684 AND...,"{'feature_0': (-4.295, -1.656), 'feature_8': (...",3,2.456,2.13,-0.33,4,CT on D (Exhaustive),42,102,0.01,0.655868,0.397926,1.345,Exhaustive,17.0,58
1,13,feature_0 <= -1.656 AND feature_8 > 0.684 AND ...,"{'feature_0': (-4.295, -1.656), 'feature_8': (...",2,4.295,3.88,-0.41,3,CT on D (Exhaustive),39,102,0.01,0.655868,0.567045,1.444,Exhaustive,17.0,58
2,88,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (0.901, 1.836), 'feature_4': (-3...",5,2.822,0.54,3.36,8,CT on D (Exhaustive),47,102,0.01,0.655868,0.431584,2.090,Exhaustive,17.0,58
3,97,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (1.836, 3.728), 'feature_4': (-3...",4,4.474,0.75,5.23,7,CT on D (Exhaustive),44,102,0.01,0.655868,0.583506,2.750,Exhaustive,17.0,58
4,98,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (1.836, 3.728), 'feature_4': (-3...",3,5.437,1.42,6.86,6,CT on D (Exhaustive),47,102,0.01,0.605487,0.697257,3.701,Exhaustive,17.0,58

In [28]:
debug(CF, Exhaustive)

Computing overlap matrix

100%|██████████| 4950/4950 [00:19<00:00, 259.90it/s]

Overlap matrix computed
[CF (Exhaustive)] Offline time: 22.84
User condition: feature_5 <= 0.665 Selectivity: 0.7458
[CF (Exhaustive)] Online time: 0.77, Total Splits: 4950, Valid: 4392

511130013it [35:48, 237846.93it/s]

KeyboardInterrupt: